---
kind: pipeline
name: Windows 1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: git
  image: plugins/docker:windows-1809
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809-amd64
    daemon_off: true
    dockerfile: docker/Dockerfile.windows.1809
    password:
      from_secret: docker_password
    purge: false
    repo: drone/git
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"

---
kind: pipeline
name: Image Manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"

depends_on:
- Windows 1809

...
